# Generated by Django 3.1.14 on 2022-06-29 13:44

from django.db import migrations

def change_evolution(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    pokemons_with_evolution = Pokemon.objects.filter(next_evolution__isnull=False)
    for pokemon in pokemons_with_evolution:
        evolutioned_pokemon = pokemon.next_evolution.first()
        evolutioned_pokemon.previous_evolution = pokemon
        pokemon.next_evolution = None
        pokemon.save()
        evolutioned_pokemon.save()


def change_evolution_backward(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    pokemons_with_evolutioned = Pokemon.objects.filter(previous_evolution__isnull=False)
    for pokemon in pokemons_with_evolutioned:
        evolutioned_pokemon = pokemon.previous_evolution.first()
        evolutioned_pokemon.next_evolution = pokemon
        pokemon.previous_evolution = None
        pokemon.save()
        evolutioned_pokemon.save()



class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_pokemon_next_evolution'),
    ]

    operations = [
        migrations.RunPython(change_evolution, change_evolution_backward),
    ]
