# Generated by Django 3.1.14 on 2022-07-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_auto_20220704_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElemetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('WATER', 'Water'), ('FIRE', 'Fire'), ('GRASS', 'Grass'), ('ELECTRO', 'Electro'), ('MAGICAL', 'Magical'), ('ICE', 'Ice')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='element_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='pokemons', to='pokemon_entities.PokemonElemetType'),
        ),
    ]
