# Generated by Django 3.1.14 on 2022-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20220705_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='element_type',
            field=models.ManyToManyField(blank=True, related_name='pokemons', to='pokemon_entities.PokemonElemetType'),
        ),
    ]
