# Generated by Django 3.1.14 on 2022-07-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20220705_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('WATER', 'Water'), ('FIRE', 'Fire'), ('GRASS', 'Grass'), ('ELECTRO', 'Electro'), ('MAGICAL', 'Magical'), ('ICE', 'Ice')], max_length=20, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PokemonElemetType',
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='element_type',
            field=models.ManyToManyField(blank=True, related_name='pokemons', to='pokemon_entities.PokemonElementType'),
        ),
    ]
