# Generated by Django 3.1.14 on 2022-07-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0020_auto_20220706_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='pokemons', to='pokemon_entities.PokemonElementType'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(default='default_pokemon_emage.png', upload_to=''),
        ),
    ]
