# Generated by Django 3.1.14 on 2022-07-06 07:09

from django.db import migrations


def set_null_to_blank_pokemon(apps, schema_editor):
    Pokemon = apps.get_model('pokemon_entities', 'Pokemon')
    pokemons_without_title_jp = Pokemon.objects.filter(title_jp__isnull=True)
    for pokemon in pokemons_without_title_jp:
        pokemon.title_jp = ''
        pokemon.save()
    pokemons_without_title_en = Pokemon.objects.filter(title_en__isnull=True)
    for pokemon in pokemons_without_title_en:
        pokemon.title_en= ''
        pokemon.save()
    pokemons_without_description = Pokemon.objects.filter(description__isnull=True)
    for pokemon in pokemons_without_title_en:
        pokemon.description= ''
        pokemon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_auto_20220706_0840'),
    ]

    operations = [
        migrations.RunPython(set_null_to_blank_pokemon)
    ]
