# Generated by Django 3.1.14 on 2022-07-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_auto_20220706_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='pokemons', to='pokemon_entities.PokemonElementType', verbose_name='Стихии покемона'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение покемона'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(choices=[('WATER', 'Water'), ('FIRE', 'Fire'), ('GRASS', 'Grass'), ('ELECTRO', 'Electro'), ('MAGICAL', 'Magical'), ('ICE', 'Ice')], max_length=20, unique=True, verbose_name='Название стихии'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pokemon_entities.pokemon', verbose_name='покемон'),
        ),
    ]
