# Generated by Django 4.0.6 on 2022-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0028_pokemonelementtype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(choices=[('WATER', 'Water'), ('FIRE', 'Fire'), ('GRASS', 'Grass'), ('ELECTRO', 'Electro'), ('MAGICAL', 'Magical'), ('ICE', 'Ice'), ('TOXIC', 'Toxic')], max_length=20, unique=True, verbose_name='Название стихии'),
        ),
    ]
