# Generated by Django 4.0.6 on 2022-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0030_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(to='pokemon_entities.pokemonelementtype', verbose_name='Более слабые стихии'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(choices=[('WATER', 'Water'), ('FIRE', 'Fire'), ('GRASS', 'Grass'), ('ELECTRO', 'Electro'), ('MAGICAL', 'Magical'), ('ICE', 'Ice'), ('TOXIC', 'Toxic'), ('STONE', 'Stone')], max_length=20, unique=True, verbose_name='Название стихии'),
        ),
    ]
